### ISSUE TITLE
Allow for branch and any other git ref to be supplied.

### ISSUE THREAD

**Issue by howardroark** [howardroark/pollinate#27]
Specifically in the case of github the schema could be `username/template#gitref`

**Comment by jedwards1211** [comment]
Do you know off the top of your head where I should put the code to check out the supplied ref?  If so maybe I can take a quick stab at this

**Comment by howardroark** [comment]
Sorry for the delay... I tend to only check in on GitHub once per week.  You can find all the code related to "fetching" in [`fetch.js`](https://github.com/howardroark/pollinate/blob/develop/lib/fetch.js#L167)

Always up for contributions!

**Comment by howardroark** [comment]
@jedwards1211 I've started a PR for this ... https://github.com/howardroark/pollinate/pull/38/files

Try it out and let me know if it works.  I have not tested it.

**Comment by jedwards1211** [comment]
Yeah, it works!  I can write tests for it.

**Comment by howardroark** [comment]
That would be great!  I kinda rushed the tests so feel free to improve anything you feel is a bit odd.

**Comment by jedwards1211** [comment]
Oh, I thought it wasn't tested yet since coverage went down, but I can try to increase coverage anyway

**Comment by howardroark** [comment]
Yeah, upping coverage is always helpful.  It would be nice to be 90% + eventually.
