### ISSUE TITLE
Parse all files except specific files/directories

### ISSUE THREAD

**Issue by matgargano** [howardroark/pollinate#32]
I'm trying to get Pollinate to work with a WordPress theme that HAS twig files within it that I don't want parsed by Pollinate, they are parsed as part of WordPress, in my project those files are in web/app/themes/template-theme/templates

I tried having the parse array something like this:

```
   "parse": [
    "*",
    "!web/app/themes/template-theme/templates"
  ],
```

but that doesn't seem to parse anything... is that a feature that I'm just not entering correctly - or something that would be a feature request?

**Comment by howardroark** [comment]
I think that's a good idea to have some kind  of "ignore" `!` indicator.  But yeah the functionality is pretty basic right now, just exact paths to files or all files.  I was thinking this would come up eventually.  Basically just do it like `.gitignore` does it I guess?

**Comment by howardroark** [comment]
In version `2.0.0` this should get you all files except the ignored directory.  Though I have not tested it ...
```
 "parse": [
    "!web/app/themes/template-theme/templates"
  ]
```

If it doesn't work then maybe reopen this issue.  Thanks!

**Comment by howardroark** [comment]
Reopening because this does not work.  I think it should also work the way you originally described anyway (not like my last comment).

**Comment by howardroark** [comment]
OK! You should now be able to do this in `2.1.0` with "glob" patterns..

```
 "parse": [
    "**",
    "!web/app/themes/template-theme/templates/**"
],
```

A single "*" path would not include subdirectories

**Comment by matgargano** [comment]
awesome will give this a go soon i hope!
