### ISSUE TITLE
Parse explicit directories

### ISSUE THREAD

**Issue by matgargano** [howardroark/pollinate#33]
When I try to add a directory to the parse array it doesn't seem to work at all, is this a feature request or something that I am doing wrong... e.g. for a repo I am trying to add all files within the `config` directory, I have tried:

```
 "parse": [
    "Capfile",
    "bower.json",
    "composer.json",
    "Gruntfile.js",
    "package.json",
    "config/*"
  ],
```

and

```
 "parse": [
    "Capfile",
    "bower.json",
    "composer.json",
    "Gruntfile.js",
    "package.json",
    "config"
  ],
```

and when I run pollinate mygitnamesapce/myproject when I run it, it does nothing... not even output the json that it typically does.

BTW, thanks for this project it's awesome!

**Comment by howardroark** [comment]
Hey, glad you like it!  Yeah... Right now it's just looking for exact paths to individual files or "*" for all files.  

I think it could be updated to treat each item in the array as a pattern for matching files.  So you could do something like `config/*`.  This tool would enable something like that ... https://github.com/isaacs/node-glob

The second thing you mention sounds like a bug... I'd be curious about more info on that :)

**Comment by howardroark** [comment]
Okay node-glob has been added in version `2.0.0`.  Try that out and see if it works for you :)

`config/*` will get you all files directly in config... `config/**`will get get you all files in all subdirectories of config.
