### ISSUE TITLE
Reduce file related dependencies

### ISSUE THREAD

**Issue by howardroark** [howardroark/pollinate#37]
This project has too many dependencies that do different things in different ways with files.  Would be nice to be able to reduce this number.  Ideally it does not involve adding more code to this project, but refactoring is totally fine.

**Comment by jedwards1211** [comment]
I know that `fs-extra` provides an alternative to `rimraf`.  However, `fs-extra` may be larger than necessary for this project, but I'm not sure.

**Comment by howardroark** [comment]
Yeah.  Was thinking maybe a bunch of the file modules try to do too many things. Stuff like `rimraf` better aligns with the unix philosophy. Single modules which do one thing and have 0 deps.

**Comment by jedwards1211** [comment]
Both have practical advantages in different situations.  For example, I do like that lodash broke up all of its functions into minimal packages, and I try to only use those as dependencies of libraries I write.  On the other hand, in a big webapp project I tend to just install the entire lodash and get on with it.

**Comment by howardroark** [comment]
I do find the `fs-extra` package to be quite useful.   I think more than one of the file packages are "multi purpose" tough.  Just one lodash is all you need :)

**Comment by howardroark** [comment]
Closing this because I have not seen any "copy" alternatives to fs-extra that have zero deps.
