### ISSUE TITLE
Move optional `.git` removal to `discard` step.

### ISSUE THREAD

**Issue by howardroark** [howardroark/pollinate#45]
This will allow a `keepHistory` option to exist in `template.json`.

**Comment by jedwards1211** [comment]
I'm kind of confused, do you mean pollinate would no longer remove `.git` by default, and the user would have to put `.git` in the `discard` part of `template.json`?

**Comment by howardroark** [comment]
Nope.  Mainly just that if that current condition is run then, `extend` will have already run and `keepHistory` will be available from any source.  I don't think it can be supplied in something like `template.json` right now.
