### ISSUE TITLE
Support for any 'platform'

### ISSUE THREAD

**Issue by howardroark** [howardroark/pollinate#6]
Both bitbucket and gitlab also offer the `user/repo` pattern.  It would be cool if pollinate could be configured to point to another platform with the same pattern.

**Comment by chadrien** [comment]
Or even more universal, allow a git repo URL as argument instead of user/repo

**Comment by howardroark** [comment]
Totally agree!  I think that should come first, have an issue for it here https://github.com/everysquare/pollinate/issues/4

Really just need to write a regex that can identify a git style URL.  Then if the first "input" matches use git bindings to grab the files. It should be as simple as cloning the repo and running Git's archive method.  I just have not yet looked into what git bindings are out there for node. I'm used to Python :P  Right now the code just gets the archive from GitHub and extracts it.

**Comment by howardroark** [comment]
@chadrien  Got something in place! 

https://github.com/everysquare/pollinate/commit/dc5bd9a52ac3685b093b2b06ba2c9d8eeb6bae6e
